### ISSUE TITLE
page not found - basepath not supported

### ISSUE THREAD

**Issue by nugusbayevkk** [codingchili/kbn-authentication-plugin#22]
hello,
i use elasticsearch 5.6.2, kibana 5.6.2.
in install node modules
then in kibana branch tag v5.6.2 i run it with npm start
kibana is now running on https://localhost:5601/jyo
```

  log   [04:27:35.166] [info][listening] basePath Proxy running at https://localhost:5601/jyo
kibana authentication plugin by codingchili@github init!
```
after open url http://localhost:5601 - it don't redirect to  https://localhost:5601/jyo/login
but to: https://localhost:5601/login

then i manual open https://localhost:5601/jyo/login
and try post query to server that post to https://localhost:5601/login - which not found.

how can i solve this problem?

**Comment by codingchili** [comment]
Hello! Thanks for submitting an issue.

The plugin has not been tested with basePath enabled.

See this documentation for disabling basePath
https://www.elastic.co/guide/en/kibana/current/development-basepath.html

Before I have updated the plugin to work with basePath you can run kibana with
`npm start -- --no-base-path`

Using a basePath is the default behavior when running in dev mode. In production it is recommended to rewrite the url to remove the basePath in a proxy, if basePath is enabled.

**Comment by nugusbayevkk** [comment]
Thanks,

next , i enter login and password: username and password, and nothing happen.
And file users.json cleaned.
Then throwed exception :

server    log   [09:57:16.296] [fatal] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at load (/opt/development/versions/5.6.2/kibana/plugins/kbn-authentication-plugin/src/authentication/file.js:22:18)
    at Object.<anonymous> (/opt/development/versions/5.6.2/kibana/plugins/kbn-authentication-plugin/src/authentication/file.js:36:1)
    at Module._compile (module.js:624:30)
    at loader (/opt/development/versions/5.6.2/kibana/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/development/versions/5.6.2/kibana/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/development/versions/5.6.2/kibana/plugins/kbn-authentication-plugin/src/authentication/auth.js:9:15)
    at Module._compile (module.js:624:30)
    at loader (/opt/development/versions/5.6.2/kibana/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/development/versions/5.6.2/kibana/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)

**Comment by codingchili** [comment]
Hi, sorry for the late reply. If by 'cleaned' you mean that you deleted the contents you will get this error. If you want to clear it you should delete it or set its contents to '{}', to make sure its valid JSON.
